### ISSUE TITLE
ossec not start 

### ISSUE THREAD

**Issue by dincerkurnaz** [wazuh/docker-ossec-elk#1]
Mac El-Capitan 10.13.1

$ docker version
Client:
 Version:      1.10.1
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   9e83765
 Built:        Thu Feb 11 19:14:21 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      linux/amd64

docker run -d -p 55000:55000 -p 1514:1514/udp -p 1515:1515 -p 514:514/udp -p 5601:5601 -v /Users/dincer/wazuh:/var/ossec/data --name ossec wazuh/ossec-elk

cat /var/ossec/logs/ossec.log
2016/04/11 12:41:28 ossec-execd(1210): ERROR: Queue '/var/ossec/queue/alerts/execq' not accessible: 'Operation not permitted'.
2016/04/11 12:41:28 ossec-analysisd(1103): ERROR: Could not open file '/var/ossec/etc/shared/ar.conf' due to [(1)-(Operation not permitted)].
2016/04/11 12:41:28 ossec-analysisd(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.

**Comment by jlruizmlg** [comment]
I @dincerkurnaz seems like Docker under OSx can't handle the ossec permissions correctly 

Container under OSX:
```
root@ece63fd12f4b:/var/ossec/etc# ls -la
total 64
drwxr-xr-x 1 ossec staff  442 Apr 11 14:29 .
drwxr-xr-x 1 ossec staff  272 Apr 11 14:29 ..
-r--rw---- 1 ossec staff   99 Feb 25 16:14 client.keys
-rw-rw---- 1 ossec staff 2842 Feb 25 16:14 internal_options.conf
-rw-rw---- 1 ossec staff  320 Feb 25 16:14 local_internal_options.conf
-r--rw---- 1 ossec staff  118 Feb 25 16:14 localtime
-rw-rw---- 1 ossec staff  113 Feb 25 16:14 ossec-init.conf
-rw-rw---- 1 ossec staff 7349 Feb 25 16:14 ossec.conf
drwxr-xr-x 1 ossec staff 2210 Feb 25 16:14 ossec_decoders
drwxr-xr-x 1 ossec staff  510 Feb 25 16:14 shared
-rw-rw-r-- 1 ossec staff 1797 Apr 11 14:29 sslmanager.cert
-rw-rw-r-- 1 ossec staff 3243 Apr 11 14:29 sslmanager.key
drwxr-xr-x 1 ossec staff  272 Feb 25 16:14 wazuh_decoders
root@ece63fd12f4b:/var/ossec/etc#
```
When the permissions need to be
Container under CentOS:
```
root@ae5108322633:/var/ossec/etc# ls -la
total 52
dr-xrwx---. 5 root ossec 4096 Apr 11 14:59 .
drwxrwxr-x. 7 root root    82 Apr 11 14:59 ..
-r--rw----. 1 root ossec   99 Feb 25 16:14 client.keys
-rw-rw----. 1 root ossec 2842 Feb 25 16:14 internal_options.conf
-rw-rw----. 1 root ossec  320 Feb 25 16:14 local_internal_options.conf
-r--rw----. 1 root ossec  118 Feb 25 16:14 localtime
-rw-rw----. 1 root root   113 Feb 25 16:14 ossec-init.conf
-rw-rw----. 1 root ossec 7349 Feb 25 16:14 ossec.conf
dr-xrwx---. 2 root ossec 4096 Feb 25 16:14 ossec_decoders
drwxrwx---. 2 root ossec 4096 Feb 25 16:14 shared
-rw-rw-r--. 1 root root  1797 Apr 11 14:59 sslmanager.cert
-rw-rw-r--. 1 root root  3243 Apr 11 14:59 sslmanager.key
dr-xrwx---. 2 root ossec 4096 Feb 25 16:14 wazuh_decoders
root@ae5108322633:/var/ossec/etc#
```
You can run the container without ```-v /Users/dincer/wazuh:/var/ossec/data``` and works nice.

But if you like to have some persistent data try to create a data volume:

```docker create -v /data --name wazuhstore wazuh/ossec-elk```

and later 

```docker run -d -p 55000:55000 -p 1514:1514/udp -p 1515:1515 -p 514:514/udp -p 5601:5601 --volumes-from wazuhdata --name ossec wazuh/ossec-elk```

more information about data volume [here ](https://docs.docker.com/engine/userguide/containers/dockervolumes/)

**Comment by dincerkurnaz** [comment]
Done! 
Thank you :)

**Comment by jlruizmlg** [comment]
you are welcome @dincerkurnaz thanks for your feedback.
