### ISSUE TITLE
Add documentation for must-change settings (e.g. API username/password)

### ISSUE THREAD

**Issue by igorgatis** [wazuh/docker-ossec-elk#11]
It would be nice if documentation included a section explaining which settings/files need to be changed in order to secure docker deployment. For instance, API username/password.

**Comment by jlruizmlg** [comment]
hi @igorgatis you are right, we will try to improve in the next release!

**Comment by jlruizmlg** [comment]
Hi @igorgatis take a look at our new repository with the new version, it's not finished yet, still a "beta", we will appreciate your feedback.

https://github.com/wazuh/wazuh-docker
