### ISSUE TITLE
Restarting OSSEC generates ossec-remoted error

### ISSUE THREAD

**Issue by pjmorr** [wazuh/docker-ossec-elk#2]
Fired up the docker container within Amazon ECS:  Here is the command I used:

```bash
docker run -d -p 55000:55000 \
-p 1514:1514/udp -p 1515:1515 \
-p 514:514/udp -p 5601:5601 \
-v /srv/ossec_mnt:/var/ossec/data \
--name ossec wazuh/ossec-elk
```
When I tried to hit the API via postman I got the error:
```json
{
  "error": 50,
  "data": "",
  "message": "Problem with import modules in command: No module named xmljson"
}
```
so, I tried to run `pip install xmljson` per the docs and it told me pip was not a valid command...  
Not to give up so easily, I then jumped into the container and ran  `apt-get install python-pip`  
Then `pip install xmljson`  
Then  when `/var/ossec/bin/ossec-control restart` gave me an error I ran:
`bin/ossec-control enable debug` followed by another `/var/ossec/bin/ossec-control restart`  
This is the output, minus some text <if you want all of it I will update>  

```bash
2016/04/13 22:12:54 adding rule: solaris_bsm_rules.xml
2016/04/13 22:12:54 adding rule: vmware_rules.xml
2016/04/13 22:12:54 adding rule: ms_dhcp_rules.xml
2016/04/13 22:12:54 adding rule: asterisk_rules.xml
2016/04/13 22:12:54 adding rule: ossec_rules.xml
2016/04/13 22:12:54 adding rule: attack_rules.xml
2016/04/13 22:12:54 adding rule: auditd_rules.xml
2016/04/13 22:12:54 adding rule: usb_rules.xml
2016/04/13 22:12:54 adding rule: opensmtpd_rules.xml
2016/04/13 22:12:54 adding rule: local_rules.xml
2016/04/13 22:12:54 ossec-analysisd: DEBUG: Read configuration ...
Started ossec-analysisd...
2016/04/13 22:12:54 ossec-logcollector: DEBUG: Starting ...
Started ossec-logcollector...
2016/04/13 22:12:54 ossec-remoted: DEBUG: Starting ...
2016/04/13 22:12:54 ossec-remoted(2301): ERROR: Definition not found for: 'remoted.pass_empty_keyfile'.   
``` 

Any ideas?

**Comment by jlruizmlg** [comment]
hi @pjmorr let me review, this morning we released a new docker version with new API version as well, can you please pull again wazuh/ossec-elk image delete the ossec container and launch again?
```
docker pull wazuh/ossec-elk
docker stop ossec
docker rm ossec
docker run -d -p 55000:55000 \
-p 1514:1514/udp -p 1515:1515 \
-p 514:514/udp -p 5601:5601 \
-v /srv/ossec_mnt:/var/ossec/data \
--name ossec wazuh/ossec-elk
```

**Comment by pjmorr** [comment]
So, did that.  Some of the REST API works without installing anything, I chose to no modify a thing.  After letting the system run for an hour I ran the following.  

```bash
docker exec -it ossec /var/ossec/bin/ossec-control restart
Deleting PID file '/var/ossec/var/run/ossec-logcollector-604.pid' not used...
Deleting PID file '/var/ossec/var/run/ossec-analysisd-600.pid' not used...
ossec-monitord not running ..
ossec-logcollector not running ..
ossec-remoted not running ..
ossec-syscheckd not running ..
ossec-analysisd not running ..
ossec-maild not running ..
ossec-execd not running ..
OSSEC HIDS v2.9.0 Stopped
Starting OSSEC HIDS v2.9.0 (by Trend Micro Inc.)...
2016/04/14 00:17:42 ossec-maild: INFO: E-Mail notification disabled. Clean Exit.
Started ossec-maild...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-logcollector...
2016/04/14 00:17:42 ossec-remoted(2301): ERROR: Definition not found for: 'remoted.pass_empty_keyfile'.
```

**Comment by jlruizmlg** [comment]
What instance type are you using? i like to try in the same environment than you

**Comment by pjmorr** [comment]
It is a 
`m3.medium`  
`amzn-ami-2015.09.f-amazon-ecs-optimized (ami-4600372c)`  
`Amazon Linux AMI 2015.09.f x86_64 ECS HVM GP2`  
There is plenty of room on the box, it's only at 20%.  
I have not tried to launch/configure it from the AWS console at this point.  
I was just doing everything from ssh on the ECS server itself.  
Making a task and what not was going to come after I figure out if I could get it working. :smile:

**Comment by jlruizmlg** [comment]
hi @pjmorr can you review if you have this line in /var/ossec/etc/internal_options.conf?
```
# Don't exit when client.keys empty
remoted.pass_empty_keyfile=0
```
if don't you can add and try again?

thanks.

**Comment by pjmorr** [comment]
well that is odd in that I created /srv/ossec_mnt about 5 min prior to spinning up this new dockerized OSSEC, but it is possible that I spun up the non-ELK version first and did not delete the directory beforehand.  I do not have that block in my internal_options.conf.  

Do I just add that or is there more that I should fix?  Or should I just delete the content out of /srv/ossec_mnt and start over?

**Comment by jlruizmlg** [comment]
Maybe this is the problem, right now the non-elk is different version than wazuh/ossec-elk, so the internal_options.conf is different as well.

You are running the ```docker run``` with a data volume, for this reason the ```internal_options.conf``` is not overwriting with the new version.

if you don't have a relevant information in this folder (client.keys, local_rules, etc), better if you just delete and start over.

On the other hand, this morning we released a new wazuh/ossec-elk version with OSSEC Wazuh Ruleset 
pull again the container to have this feature.
```
docker pull wazuh/ossec-elk
docker stop ossec
docker rm ossec
docker run -d -p 55000:55000 \
-p 1514:1514/udp -p 1515:1515 \
-p 514:514/udp -p 5601:5601 \
-v /srv/ossec_mnt:/var/ossec/data \
--name ossec wazuh/ossec-elk
```

**Comment by pjmorr** [comment]
i will clean up and do so, thanks.

**Comment by jlruizmlg** [comment]
Let me know if it works for you

**Comment by santiago-bassett** [comment]
@pjmorr did you get it to work?

**Comment by pjmorr** [comment]
Sorry for the delay, so far I have not been successful.  I am wiping the container and doing a re pull to see if I can get it working today.

**Comment by jlruizmlg** [comment]
Please tray without your ``/srv/ossec_mnt``or give other different, empty folder, just for a complete fresh installation

**Comment by pjmorr** [comment]
yep thats what im going to do, complete re-do

**Comment by yurmuki** [comment]
root@server:/var/ossec/bin# /etc/init.d/ossec restart
Deleting PID file '/var/ossec/var/run/ossec-remoted-2920.pid' not used...
Killing ossec-monitord .. 
Killing ossec-logcollector .. 
ossec-remoted not running ..
Killing ossec-syscheckd .. 
Killing ossec-analysisd .. 
Killing ossec-maild .. 
ossec-execd not running ..
OSSEC HIDS v2.8.3 Stopped
Starting OSSEC HIDS v2.8.3 (by Trend Micro Inc.)...
Started ossec-maild...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-logcollector...
Started ossec-remoted...
Started ossec-syscheckd...
Started ossec-monitord...
Completed.



root@server:/var/ossec/bin# ./manage_agents 


****************************************
* OSSEC HIDS v2.8.3 Agent manager.     *
* The following options are available: *
****************************************
   (A)dd an agent (A).
   (E)xtract key for an agent (E).
   (L)ist already added agents (L).
   (R)emove an agent (R).
   (Q)uit.
Choose your action: A,E,L,R or Q: A

- Adding a new agent (use '\q' to return to the main menu).
  Please provide the following:
   * A name for the new agent: server.com
   * The IP Address of the new agent: 192.168.0.162
   * An ID for the new agent[001]: 
Agent information:
   ID:001
   Name:server.com
   IP Address:192.168.0.162

Confirm adding it?(y/n): y
Agent added.


****************************************
* OSSEC HIDS v2.8.3 Agent manager.     *
* The following options are available: *
****************************************
   (A)dd an agent (A).
   (E)xtract key for an agent (E).
   (L)ist already added agents (L).
   (R)emove an agent (R).
   (Q)uit.
Choose your action: A,E,L,R or Q: Q

** You must restart OSSEC for your changes to take effect.

manage_agents: Exiting ..


root@server::/var/ossec/bin# /etc/init.d/ossec restart
Killing ossec-monitord .. 
Killing ossec-logcollector .. 
Killing ossec-remoted .. 
Killing ossec-syscheckd .. 
Killing ossec-analysisd .. 
Killing ossec-maild .. 
ossec-execd not running ..
OSSEC HIDS v2.8.3 Stopped
Starting OSSEC HIDS v2.8.3 (by Trend Micro Inc.)...
Started ossec-maild...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-logcollector...
Started ossec-remoted...
Started ossec-syscheckd...
Started ossec-monitord...
Completed.

We need to add an agent to start remoted service.
