### ISSUE TITLE
ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.

### ISSUE THREAD

**Issue by cloud101** [wazuh/docker-ossec-elk#3]
Initially I couldn't get it started because an option was missing in the internal_options.conf file. After manually adding 

```
# Don't exit when client.keys empty
remoted.pass_empty_keyfile=0
```

I tried restarting and this resulted in the following errors:

```
root@dockerhost:/opt/ossec/etc# docker exec -it ossec /var/ossec/bin/ossec-control restart
Deleting PID file '/var/ossec/var/run/ossec-logcollector-969.pid' not used...
Deleting PID file '/var/ossec/var/run/ossec-analysisd-964.pid' not used...
ossec-monitord not running ..
ossec-logcollector not running ..
ossec-remoted not running ..
ossec-syscheckd not running ..
ossec-analysisd not running ..
ossec-maild not running ..
ossec-execd not running ..
OSSEC HIDS v2.9.0 Stopped
Starting OSSEC HIDS v2.9.0 (by Trend Micro Inc.)...
2016/08/27 07:27:43 ossec-maild: INFO: E-Mail notification disabled. Clean Exit.
Started ossec-maild...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-logcollector...
Started ossec-remoted...
2016/08/27 07:27:46 ossec-syscheckd(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2016/08/27 07:27:46 rootcheck(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2016/08/27 07:27:54 ossec-syscheckd(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2016/08/27 07:27:54 rootcheck(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2016/08/27 07:28:07 ossec-syscheckd(1210): ERROR: Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2016/08/27 07:28:07 rootcheck(1211): ERROR: Unable to access queue: '/var/ossec/queue/ossec/queue'. Giving up..
ossec-syscheckd did not start correctly.
root@dockerhost:/opt/ossec/etc#

```

Any ideas?  Docker is running on Ubuntu 14.04.5 LTS

**Comment by jlruizmlg** [comment]
Hi @cloud101 , is this container an upgrade from an old version?

Do you have any agent running already in this new container?

**Comment by cloud101** [comment]
@jlruizmlg no, it's a brand new installation from scratch

**Comment by jlruizmlg** [comment]
Hi @cloud101, so you doesn't have a previous installation? looks strange because the option: 
```
# Don't exit when client.keys empty
remoted.pass_empty_keyfile=0
```
doesn't exist in previous versions.
Did you have any ossec with docker working in this machine before?
Thanks.

**Comment by jlruizmlg** [comment]
Hi @cloud101, Do you have any update in this issue? Thanks!

**Comment by cloud101** [comment]
I did a complete install from scratch . The image was the latest one available from dockerhub. Now it seems to work. No idea what happened :/

**Comment by jlruizmlg** [comment]
We have two containers in dockerhub, one OSSEC 2.8.3 (only the server) and the other OSSEC Wazuh + ELK.  Is it possible that you install the 2.8.3 version and overwrite with the ELK sharing the same ossec_mnt folder?
I try to understand why from a fresh installation you had this problem.

**Comment by Jsgoller1** [comment]
@cloud101 not sure if you and I are having the same problem, but I got the same error messages because I was mounting the directories described [in the docs](http://documentation.wazuh.com/en/latest/ossec_docker.html) (`-v /somepath/elasticsearch:/var/lib/elasticsearch -v /somepath/ossec_mnt:/var/ossec/data`, with `somepath` changed) with the wrong permissions; if you start the container as-is, they should be correct (some of them are owned by ossec, and `/var/lib/elasticsearch` ones is owned by the elasticsearch user) but it's easy to accidentally mount them as owned by root.

**Comment by jlruizmlg** [comment]
hi @cloud101 any update about this issue?
