### ISSUE TITLE
Remote Syslog Server

### ISSUE THREAD

**Issue by ooola** [wazuh/docker-ossec-elk#5]
Hi,

Have the remote syslog options been tested with this docker-ized configuration?

When enabled in the environment, and thus in ossec.conf the confirmation in /var/ossec/logs/ossec.log never appear. According to http://ossec-docs.readthedocs.io/en/latest/manual/output/syslog-output.html lines such as 

12:55:16 ossec-csyslogd: INFO: Forwarding alerts via syslog to: ‘10.1.1.1:514′.

should appear. And unsurprisingly the remote syslog servers never see any messages.

Note that on a manual (non docker) setup remote syslogging works fine when enabled in ossec.conf.

-Ola

**Comment by jlruizmlg** [comment]
Hi @ooola i found a error in the configuration, the syslog port was wrong, sorry about that, i just fix in the commit f619617 . 

Please pull the container again and try.

Don't forget to do a backup from your Ossec and Elasticsearch before you pull the container .

**Comment by ooola** [comment]
Thanks!

**Comment by jlruizmlg** [comment]
Let us know if works thanks!
