### ISSUE TITLE
Can't connect to the REST API

### ISSUE THREAD

**Issue by zurekx** [wazuh/docker-ossec-elk#7]
When I try to connect to OSSEC REST API I receive an error 401 Unauthorized

The problem is with authnetication, when authentication is disabled the api works correctly.

**Comment by jlruizmlg** [comment]
hi @zurekx you are right, nodejs was in a old version, i just push an update in the container, please try and let us know.

**Comment by jlruizmlg** [comment]
hi @zurekx you have any feedback from this issue?
