### ISSUE TITLE
Kibana memory leak

### ISSUE THREAD

**Issue by spencescu** [wazuh/docker-ossec-elk#8]
I have downloaded the OSSEC-ELK container. Unfortunately it is unusable due to a memory leak of the Kibana component. After a few hours, the host system runs out of memory and it needs rebooted. I tried to implement the memory limit mentioned in some of the online forums, limiting the memory to 250 MB, but it still made the server crash. It would be very useful to release an update since this is a great way of deploying OSSEC.

Thanks,
Sherman

**Comment by jlruizmlg** [comment]
hi @spencescu in a few days we will release the new Wazuh version 2.0, this version will work with ELK 5, meanwhile you can try with workaround 

http://documentation.wazuh.com/en/latest/ossec_elk_kibana.html#kibana-on-low-memory-systems

i hope it helps.

**Comment by spencescu** [comment]
Hi @jlruizmlg thank you for the update. I tried the workaround and it didn't work for me. I will wait for the update.

**Comment by jlruizmlg** [comment]
@spencescu you have the kibana version 4.5.4 right? 

**/opt/kibana/bin/kibana**

```
#!/bin/sh
SCRIPT=$0

# SCRIPT may be an arbitrarily deep series of symlinks. Loop until we have the concrete path.
while [ -h "$SCRIPT" ] ; do
  ls=$(ls -ld "$SCRIPT")
  # Drop everything prior to ->
  link=$(expr "$ls" : '.*-> \(.*\)$')
  if expr "$link" : '/.*' > /dev/null; then
    SCRIPT="$link"
  else
    SCRIPT=$(dirname "$SCRIPT")/"$link"
  fi
done

DIR="$(dirname "${SCRIPT}")/.."
NODE="${DIR}/node/bin/node"
test -x "$NODE" || NODE=$(which node)
if [ ! -x "$NODE" ]; then
  echo "unable to find usable node.js executable."
  exit 1
fi
NODE_OPTIONS="${NODE_OPTIONS:=--max-old-space-size=250}"
exec "${NODE}" $NODE_OPTIONS "${DIR}/src/cli" ${@}
```

**/opt/kibana/bin/kibana.bat**

```
@echo off

SETLOCAL

set SCRIPT_DIR=%~dp0
for %%I in ("%SCRIPT_DIR%..") do set DIR=%%~dpfI

set NODE=%DIR%\node\node.exe

WHERE /Q node
IF %ERRORLEVEL% EQU 0 (
  for /f "delims=" %%i in ('WHERE node') do set SYS_NODE=%%i
)

If Not Exist "%NODE%" (
  IF Exist "%SYS_NODE%" (
    set "NODE=%SYS_NODE%"
  ) else (
    Echo unable to find usable node.js executable.
    Exit /B 1
  )
)

if "%NODE_OPTIONS%" == "" (
  set NODE_OPTIONS=--max-old-space-size=250
)


TITLE Kibana Server
"%NODE%" %NODE_OPTIONS% "%DIR%\src\cli" %*

:finally

ENDLOCAL
```

**Comment by spencescu** [comment]
Yes, I have kibana 4.5.4 ... I only changed the first file, if the upgrade takes a while longer I will change the second and try again, but would much rather prefer to run the latest version.

Many thanks again for your help!
Sherman

**Comment by spencescu** [comment]
Oh but the second one is for windows... so I really don't understand why it didn't work. Maybe my VM has very little memory. I will check.

**Comment by jlruizmlg** [comment]
Hi @spencescu it's a container, the second one should be inside the container, no matter if you run the container in Windows or Linux.

**Comment by barahon** [comment]
The low-memory config worked for me. My container had been hanging every day, but the low-memory config has allowed to stay up for 3 days so far.
